### ISSUE TITLE
Query parameters are not added

### ISSUE THREAD

**Issue by tsuharesu** [SchibstedSpain/Protein#14]
**Is your feature request related to a problem? Please describe.**
If the endpoint has query parameters, the generated method doesn't add it.

**Describe the solution you'd like**
Add @Query parameters to methods.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Awesome plugin! Really helpful.

**Comment by ferranpons** [comment]
Hi @tsuharesu !

Please could you give more info about the issue? An example of the json from swagger would be helpful.

Which version of the plugin are you using?


Thanks!

**Comment by ferranpons** [comment]
@tsuharesu I see. Many thanks for the info. I'll solve it as soon as I can. 😉

**Comment by ferranpons** [comment]
@tsuharesu version 1.1.0 is ready for download. Includes the fix for this issue. If you still have problems please re-open this issue or create a new one.

Many thanks for your help!
