### ISSUE TITLE
Nullability

### ISSUE THREAD

**Issue by JEuler** [SchibstedSpain/Protein#20]
Hi! Does it support the nullability fields? For example, if the backend will send the null as I understand, the app will be closed because of non-null fields in data classes.

**Comment by JEuler** [comment]
Nono, I meant the situation when I have the following declaration:
```data class Skill(@SerializedName("name") var name: String,
                @SerializedName("alias") var alias: String)```

What will happen if there is a null from backend? Crash? For example, some error on backend (missing field) and we have null as `name` and `alias`, or maybe only the `alias`?

**Comment by ferranpons** [comment]
String Nullability is not contemplated right now. If your backend is sending a null content you may want to avoid that situation. AFAIK Swagger 2.0 does not support nullable parameters, Open Api 3.0 does support it but this plugin is only targeting version 2. 
As an alternative you could add "?" manually on the interface, like:

`@SerializedName("alias") var alias: String?`

**Comment by JEuler** [comment]
Okay, I understand! Thx for information!

**Comment by ferranpons** [comment]
You're welcome!

If you have more questions don't hesitate and open a new issue 😉
