### ISSUE TITLE
interface is Empty

### ISSUE THREAD

**Issue by axti** [SchibstedSpain/Protein#21]
Hi.
Do you know why the objects created successfully, but the interface is empty?

**Comment by ferranpons** [comment]
Hi @axti 

Please could you give me more info about it? An example of the swagger json used would be helpful.

Thanks!

**Comment by ferranpons** [comment]
Hi @axti 

Any news about this? Please could you provide more info?


Thanks!

**Comment by ferranpons** [comment]
@axti I'm closing this issue because I had no response. If you're still experiencing this issue please re-open it.
