### ISSUE TITLE
We should have an option to decide about retrofit absolute/relative request path

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [SchibstedSpain/Protein#30]
**Is your feature request related to a problem? Please describe.**
I'm  frustrated when I have to remove the first slash / for all Retrofit's annotations, like changing:
@POST("/person/data") 
to:
@POST("person/data") 

**Describe the solution you'd like**
This involves the case when the baseUrl for retrofit is nested, like:
"https://myApi/myEndpoint/v1/"

**Describe alternatives you've considered**
The alternative is to manually go though the file and remove slashes.

**Additional context**
We should have a checkbox in a plugin to check if we want absolute paths beginning with "/" (this would mean that "/myEndpoint/v1" would be trimmed in the basePath. Or if whether we want relative paths (without "/" at the beginning)

**Comment by MichalDanielDobrzanski** [comment]
Awesome, thank you!

**Comment by ferranpons** [comment]
@MichalDanielDobrzanski solved on the latest version (1.1.3) that is submitted to the JetBrains plugin store. Will be published soon.

I'm closing the issue. If you still experience the same issue with the latest version please re-open it or create a new issue. Many thanks for reporting it.
