### ISSUE TITLE
Type of Body parameters seems wrong.

### ISSUE THREAD

**Issue by carlosefonseca** [SchibstedSpain/Protein#5]
Just tried Protein and it's looking pretty great, but I'm seeing something wrong:
the `@Body argument: Type`  seems to be using the parameter name for the Type, instead of the schema defined on the swagger. All `@Body` arguments on the generated `ApiInterface` are unresolved and reference incorrect class names. The correct classes were created but aren't used.

**To Reproduce**
Generate code for a swagger that contains something like this in a request description:
```
  "parameters": [
          {
            "name": "requestPatch",
            "in": "body",
            "description": "Patch object containing the new state value",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RequestUpdateStateDTO"
            }
          }
        ],
```

I believe this should generate something like 
```
fun foo(@Body requestPatch: RequestUpdateStateDTO)
```

but it actually generates something like
```
fun foo(@Body requestPatch: RequestPatch)
```

**Info Required**
- Plugin version 1.0

**Comment by ferranpons** [comment]
Hi @carlosefonseca 

Sure, it should generate the definition that you expect. I'll check what's happening and solve the issue.

Many thanks for reporting it! 😉

**Comment by ferranpons** [comment]
@carlosefonseca new version 1.0.1 have just been submitted to JetBrains. Includes the fix for this issue. Soon will be available for download.

I'll ping you as soon is available.

**Comment by ferranpons** [comment]
@carlosefonseca New version 1.0.1 available for download. If you still have issues related to this please reopen the issue.

Many thanks for your help!
