### ISSUE TITLE
Plugin assumes you've only got one project open and that the project you're working with is the first one

### ISSUE THREAD

**Issue by liminal** [SchibstedSpain/Protein#8]
Code blindly assumes you want to work against first open project. 

**To Reproduce**
1. Open more than one project in IDE
2. Select a project window that isn't the first one
3. Select New > Protein - Add new rest api interface
4. You now get to select modules from the _first_ project. Not whichever you actually tried to add stuff to

**Expected behavior**
You should be able to select from the modules in the active project

**Info Required**
- Which version of the plugin do you actually use?
1.0.0

I assume that this is a result of the lines in `StorageUtils.java` where getting the first of the open projects from the project manager is hard coded.

https://github.com/SchibstedSpain/Protein/blob/629e7206f2697df2e730f41598b6042553a9b763/src/main/java/protein/common/StorageUtils.java#L24

https://github.com/SchibstedSpain/Protein/blob/629e7206f2697df2e730f41598b6042553a9b763/src/main/java/protein/common/StorageUtils.java#L31

**Comment by ferranpons** [comment]
Hi @liminal 

That behavior was not contemplated, it was mean to work with only one project at a time. I'll create a fix as soon as possible.

Many thanks for reporting it!

**Comment by ferranpons** [comment]
@liminal I see your point of view and I'm agree with that. I'll correct it as soon as I can.

**Comment by ferranpons** [comment]
@liminal new version 1.0.1 have just been submitted to JetBrains. Includes the fix for this issue. Soon will be available for download.

I'll ping you as soon is available.

**Comment by ferranpons** [comment]
@liminal New version 1.0.1 available for download. If you still have issues related to this please reopen the issue.

Many thanks for your help!

**Comment by liminal** [comment]
You probably want to fix https://github.com/SchibstedSpain/Protein/blob/629e7206f2697df2e730f41598b6042553a9b763/src/main/java/protein/common/StorageUtils.java#L40 as well.

**Comment by ferranpons** [comment]
@liminal I fixed that too. Thanks!
